from __future__ import annotations

import json
import shutil
import tempfile
import threading
import unittest
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

from src.rhizome_sync_facade import default_data_dir, make_server


def _stop_server(server) -> None:
    server.shutdown()
    server.server_close()


def _get_json(base_url: str, path: str):
    with urllib.request.urlopen(f"{base_url}{path}", timeout=3) as response:
        assert response.headers["Content-Type"].startswith("application/json")
        return json.loads(response.read().decode("utf-8"))


def _get_json_from_file(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def _post_json(base_url: str, path: str, payload):
    body = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        f"{base_url}{path}",
        data=body,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request, timeout=3) as response:
        assert response.headers["Content-Type"].startswith("application/json")
        return json.loads(response.read().decode("utf-8"))


def _run_server(data_dir: Path, node_id: str = "rhizome_01", state_dir: Path | None = None):
    server = make_server("127.0.0.1", 0, data_dir, node_id=node_id, state_dir=state_dir)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    host, port = server.server_address
    return server, f"http://{host}:{port}"


def _policy_packet(target_node_id: str = "rhizome_01") -> dict:
    created_at = datetime.now(timezone.utc).replace(microsecond=0)
    valid_until = created_at + timedelta(hours=12)
    created = created_at.strftime("%Y-%m-%dT%H:%M:%SZ")
    valid = valid_until.strftime("%Y-%m-%dT%H:%M:%SZ")
    return {
        "schema_version": "1.0",
        "created_at": created,
        "origin_node_id": "pollen_01",
        "signature": None,
        "policy_id": f"pkt_{target_node_id}_pollen_visit_test",
        "target_node_id": target_node_id,
        "valid_until": valid,
        "version_chain": ["pkt_seed", f"pkt_{target_node_id}_pollen_visit_test"],
        "mode_default": "conservative",
        "policy_origin": "pollen-visit",
        "policy_scope": "transient",
        "rules": {
            "watering_window": {
                "start_hour_local": 6,
                "end_hour_local": 9,
            },
            "soil_moisture_thresholds": {
                "parcel_a": {
                    "min_pct": 35.0,
                    "target_pct": 50.0,
                }
            },
            "max_watering_duration_s": 30,
            "daily_water_budget_liters": 4.0,
            "tank_minimum_pct": 20.0,
            "require_vision_confirmation": False,
            "conservative_triggers": ["pollen_visit_voice_policy"],
        },
        "rationale": "Policy generated by Pollen Mini-Evaluator test.",
        "notes": "transient voice-to-policy test",
    }


class SyncFacadeTest(unittest.TestCase):
    def test_pollen_read_endpoints_return_contract_shapes(self):
        server, base_url = _run_server(default_data_dir())
        try:
            status = _get_json(base_url, "/status")
            snapshot = _get_json(base_url, "/snapshot/latest")
            receipts = _get_json(base_url, "/receipts")
            explanation = _get_json(base_url, f"/explain/decision/{receipts[0]['decision_id']}")
        finally:
            _stop_server(server)

        self.assertEqual(status["status"], "ready")
        self.assertEqual(status["mode"], "read_only_facade")
        self.assertEqual(status["node_id"], "rhizome_01")
        self.assertTrue(snapshot["snapshot_id"])
        self.assertGreaterEqual(snapshot["sensors"]["tank_level_pct"], 0)
        self.assertIsInstance(receipts, list)
        self.assertTrue(receipts[0]["decision_id"])
        self.assertEqual(explanation["source"], "deterministic_receipt_explainer")
        self.assertIn(receipts[0]["action"], explanation["explanation"])

    def test_explanation_can_be_localized_to_english(self):
        server, base_url = _run_server(default_data_dir())
        try:
            receipts = _get_json(base_url, "/receipts")
            explanation = _get_json(
                base_url,
                f"/explain/decision/{receipts[0]['decision_id']}?locale=en",
            )
        finally:
            _stop_server(server)

        self.assertEqual(explanation["locale"], "en")
        self.assertIn("Rhizome executed", explanation["explanation"])

    def test_explanation_respects_not_executed_water_candidate(self):
        with tempfile.TemporaryDirectory() as tmp:
            data_dir = Path(tmp)
            shutil.copy(default_data_dir() / "rhizome_snapshot.json", data_dir / "rhizome_snapshot.json")
            receipt = _get_json_from_file(default_data_dir() / "decision_receipt.json")
            receipt["decision_id"] = "rec_observe_mode"
            receipt["executed"] = False
            receipt["execution_details"] = None
            receipt["blocked_reason"] = "OBSERVE_MODE_EXECUTE_WATER_FALSE"
            (data_dir / "decision_receipt.json").write_text(json.dumps(receipt), encoding="utf-8")
            server, base_url = _run_server(data_dir)
            try:
                explanation = _get_json(base_url, "/explain/decision/rec_observe_mode?locale=en")
            finally:
                _stop_server(server)

        self.assertIn("proposed WATER_A", explanation["explanation"])
        self.assertIn("did not execute", explanation["explanation"])
        self.assertNotIn("executed WATER_A", explanation["explanation"])

    def test_visit_summary_is_smart_button_payload(self):
        server, base_url = _run_server(default_data_dir())
        try:
            summary = _get_json(base_url, "/summary/since?locale=es")
            future_summary = _get_json(
                base_url,
                "/summary/since?since=2099-01-01T00:00:00Z&locale=en",
            )
        finally:
            _stop_server(server)

        self.assertEqual(summary["node_id"], "rhizome_01")
        self.assertEqual(summary["source"], "deterministic_visit_summary")
        self.assertEqual(summary["severity"], "attention")
        self.assertEqual(summary["counts"]["total"], 2)
        self.assertEqual(summary["counts"]["water"], 1)
        self.assertEqual(summary["counts"]["water_proposed"], 1)
        self.assertIn("Durante tu ausencia", summary["summary"])
        self.assertEqual(future_summary["counts"]["total"], 0)
        self.assertEqual(future_summary["locale"], "en")

    def test_second_rhizome_demo_data_can_run_on_another_port(self):
        data_dir = default_data_dir().parents[2] / "rhizome" / "demo_data" / "rhizome_02"
        server, base_url = _run_server(data_dir, node_id="rhizome_02")
        try:
            status = _get_json(base_url, "/status")
            snapshot = _get_json(base_url, "/snapshot/latest")
            summary = _get_json(base_url, "/summary/since?locale=en")
        finally:
            _stop_server(server)

        self.assertEqual(status["node_id"], "rhizome_02")
        self.assertEqual(snapshot["origin_node_id"], "rhizome_02")
        self.assertEqual(summary["node_id"], "rhizome_02")
        self.assertTrue(summary["simulation"])

    def test_receipts_since_filter_uses_created_at(self):
        server, base_url = _run_server(default_data_dir())
        try:
            all_receipts = _get_json(base_url, "/receipts")
            future_receipts = _get_json(base_url, "/receipts?since=2099-01-01T00:00:00Z")
        finally:
            _stop_server(server)

        self.assertGreaterEqual(len(all_receipts), 1)
        self.assertEqual(future_receipts, [])

    def test_explain_missing_decision_returns_structured_404(self):
        server, base_url = _run_server(default_data_dir())
        try:
            try:
                _get_json(base_url, "/explain/decision/not-real")
            except urllib.error.HTTPError as exc:
                payload = json.loads(exc.read().decode("utf-8"))
                status = exc.code
            else:
                raise AssertionError("expected HTTPError")
        finally:
            _stop_server(server)

        self.assertEqual(status, 404)
        self.assertEqual(payload, {"error": "decision_not_found", "decision_id": "not-real"})

    def test_missing_data_file_is_service_unavailable(self):
        with tempfile.TemporaryDirectory() as tmp:
            data_dir = Path(tmp)
            shutil.copy(default_data_dir() / "decision_receipt.json", data_dir / "decision_receipt.json")
            server, base_url = _run_server(data_dir)
            try:
                try:
                    _get_json(base_url, "/snapshot/latest")
                except urllib.error.HTTPError as exc:
                    payload = json.loads(exc.read().decode("utf-8"))
                    status = exc.code
                else:
                    raise AssertionError("expected HTTPError")
            finally:
                _stop_server(server)

        self.assertEqual(status, 503)
        self.assertEqual(payload["error"], "data_file_missing")

    def test_post_policy_accepts_pollen_visit_packet_and_sets_active_policy(self):
        with tempfile.TemporaryDirectory() as tmp:
            state_dir = Path(tmp) / "state"
            server, base_url = _run_server(default_data_dir(), state_dir=state_dir)
            try:
                policy = _policy_packet()
                ack = _post_json(base_url, "/policy", policy)
                active = _get_json(base_url, "/policy/active")
                status = _get_json(base_url, "/status")
                active_policy_exists = (state_dir / "active_policy.json").exists()
            finally:
                _stop_server(server)

        self.assertEqual(ack["status"], "accepted")
        self.assertEqual(ack["policy_origin"], "pollen-visit")
        self.assertEqual(ack["policy_scope"], "transient")
        self.assertFalse(ack["hard_limits_checked_by_facade"])
        self.assertEqual(active["policy"]["policy_id"], policy["policy_id"])
        self.assertEqual(status["active_policy_id"], policy["policy_id"])
        self.assertTrue(active_policy_exists)

    def test_post_policy_rejects_missing_policy_origin(self):
        with tempfile.TemporaryDirectory() as tmp:
            server, base_url = _run_server(default_data_dir(), state_dir=Path(tmp))
            try:
                policy = _policy_packet()
                policy.pop("policy_origin")
                try:
                    _post_json(base_url, "/policy", policy)
                except urllib.error.HTTPError as exc:
                    payload = json.loads(exc.read().decode("utf-8"))
                    status = exc.code
                else:
                    raise AssertionError("expected HTTPError")
            finally:
                _stop_server(server)

        self.assertEqual(status, 400)
        self.assertEqual(payload["reason_code"], "policy_origin_invalid")

    def test_post_policy_rejects_target_node_mismatch(self):
        with tempfile.TemporaryDirectory() as tmp:
            server, base_url = _run_server(default_data_dir(), node_id="rhizome_01", state_dir=Path(tmp))
            try:
                policy = _policy_packet(target_node_id="rhizome_02")
                try:
                    _post_json(base_url, "/policy", policy)
                except urllib.error.HTTPError as exc:
                    payload = json.loads(exc.read().decode("utf-8"))
                    status = exc.code
                else:
                    raise AssertionError("expected HTTPError")
            finally:
                _stop_server(server)

        self.assertEqual(status, 409)
        self.assertEqual(payload["reason_code"], "target_node_mismatch")

    def test_post_policy_rejects_expired_policy(self):
        with tempfile.TemporaryDirectory() as tmp:
            server, base_url = _run_server(default_data_dir(), state_dir=Path(tmp))
            try:
                policy = _policy_packet()
                created_at = datetime.now(timezone.utc).replace(microsecond=0) - timedelta(hours=13)
                valid_until = datetime.now(timezone.utc).replace(microsecond=0) - timedelta(hours=1)
                policy["created_at"] = created_at.strftime("%Y-%m-%dT%H:%M:%SZ")
                policy["valid_until"] = valid_until.strftime("%Y-%m-%dT%H:%M:%SZ")
                try:
                    _post_json(base_url, "/policy", policy)
                except urllib.error.HTTPError as exc:
                    payload = json.loads(exc.read().decode("utf-8"))
                    status = exc.code
                else:
                    raise AssertionError("expected HTTPError")
            finally:
                _stop_server(server)

        self.assertEqual(status, 400)
        self.assertEqual(payload["reason_code"], "policy_expired")
