#!/usr/bin/env bash
set -euo pipefail

FACADE_URL="${FACADE_URL:-http://127.0.0.1:13010}"
TARGET_NODE_ID="${TARGET_NODE_ID:-rhizome_01}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

"$PYTHON_BIN" - "$FACADE_URL" "$TARGET_NODE_ID" <<'PY'
import json
import sys
import urllib.request
from datetime import datetime, timedelta, timezone

base_url = sys.argv[1].rstrip("/")
target_node_id = sys.argv[2]


def zulu(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def get_json(path: str):
    with urllib.request.urlopen(base_url + path, timeout=5) as response:
        return json.loads(response.read().decode("utf-8"))


def post_json(path: str, payload: dict):
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    request = urllib.request.Request(
        base_url + path,
        data=body,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request, timeout=5) as response:
        return json.loads(response.read().decode("utf-8"))


created_at = datetime.now(timezone.utc).replace(microsecond=0)
valid_until = created_at + timedelta(hours=12)
policy_id = f"pkt_{target_node_id}_pollen_visit_{created_at.strftime('%Y%m%dT%H%M%SZ')}"
policy = {
    "schema_version": "1.0",
    "created_at": zulu(created_at),
    "origin_node_id": "pollen_01",
    "signature": None,
    "policy_id": policy_id,
    "target_node_id": target_node_id,
    "valid_until": zulu(valid_until),
    "version_chain": ["pkt_seed", policy_id],
    "mode_default": "conservative",
    "policy_origin": "pollen-visit",
    "policy_scope": "transient",
    "rules": {
        "watering_window": {
            "start_hour_local": 6,
            "end_hour_local": 9,
        },
        "soil_moisture_thresholds": {
            "parcel_a": {
                "min_pct": 35.0,
                "target_pct": 50.0,
            }
        },
        "max_watering_duration_s": 30,
        "daily_water_budget_liters": 4.0,
        "tank_minimum_pct": 20.0,
        "require_vision_confirmation": False,
        "conservative_triggers": ["pollen_visit_voice_policy"],
    },
    "rationale": "Policy generated by Pollen Mini-Evaluator smoke.",
    "notes": "transient voice-to-policy smoke",
}

ack = post_json("/policy", policy)
active = get_json("/policy/active")

if ack.get("status") != "accepted":
    raise SystemExit(f"bad ack: {ack}")
if ack.get("policy_id") != policy_id:
    raise SystemExit(f"policy_id mismatch: {ack}")
if active.get("policy", {}).get("policy_id") != policy_id:
    raise SystemExit(f"active policy mismatch: {active}")
if ack.get("hard_limits_checked_by_facade") is not False:
    raise SystemExit(f"facade must not claim hard-limit validation: {ack}")

print(
    json.dumps(
        {
            "status": "ok",
            "facade_url": base_url,
            "target_node_id": target_node_id,
            "policy_id": policy_id,
            "active_for_next_decision": ack.get("active_for_next_decision"),
            "hard_limits_checked_by_facade": ack.get("hard_limits_checked_by_facade"),
        },
        ensure_ascii=False,
        separators=(",", ":"),
    )
)
PY
