# Pollen — Gradle properties

# Usar AndroidX (requerido por Compose y todas las libs modernas)
android.useAndroidX=true
android.nonTransitiveRClass=true

# JVM
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin
kotlin.code.style=official

# Performance
org.gradle.parallel=true
org.gradle.caching=true
