# Pollen — Gradle properties

# Usar AndroidX (requerido por Compose y todas las libs modernas)
android.useAndroidX=true
android.nonTransitiveRClass=true

# JVM
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin
kotlin.code.style=official

# Performance
org.gradle.parallel=true
org.gradle.caching=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
